# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions


PS1="\[\033[1;33;1;32m\]\u@\h:\[\033[1;31m\]\w$ \[\033[0m\]\[\033[0m\]"


export UTILS=~/devutils

export JAVA_HOME=$UTILS/jdk1.8.0_144
export MAVEN_HOME=$UTILS/apache-maven-3.3.3
export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH

export HADOOP_INSTALL=$UTILS/hadoop-2.7.4
export HADOOP_PREFIX=$HADOOP_INSTALL 
export PATH=$PATH:$HADOOP_INSTALL/bin 
export PATH=$PATH:$HADOOP_INSTALL/sbin 
export HADOOP_MAPRED_HOME=$HADOOP_INSTALL 
export HADOOP_COMMON_HOME=$HADOOP_INSTALL 
export HADOOP_HDFS_HOME=$HADOOP_INSTALL 
export YARN_HOME=$HADOOP_INSTALL 
export HADOOP_CONF_DIR=$HADOOP_INSTALL/etc/hadoop 
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native 
export HADOOP_OPTS="-Djava.library.path=$HADOOP_INSTALL/lib"


export PATH=$UTILS/pig-0.17.0/bin:$UTILS/hadoop_scripts/:$HADOOP_INSTALL/bin:$HADOOP_INSTALL/sbin:$UTILS/spark-2.2.0-bin-hadoop2.7/bin:$PATH

export PATH="$PATH:/opt/mssql-tools/bin"
export PATH=$PATH:$HOME/dotnet
